easy_admin:
    design:
        menu: 
          - { label: 'Public Homepage', route: 'homepage' ,default: true }
        form_theme: ['@EasyAdmin/form/bootstrap_4.html.twig', '@EasyAdmin/form/bootstrap_4.html.twig']
    list:
        actions:
          - { name: 'edit', icon: 'pencil' , label: false }
          - { name: 'delete', icon: 'trash' , label: false }
        max_results: 50
    entities:
        # List the entity class name you want to manage
        FosUser:
            class: App\Entity\FosUser
            list:
              actions: ['-new',{ name: 'edit', icon: 'pencil' , label: false },{ name: 'delete', icon: 'trash' , label: false }]
        Delegacion:
              class: App\Entity\Delegacion
        Estados:
              class: App\Entity\Estados
        Flotillas:
              class: App\Entity\Flotillas
              form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'nombre', type: 'text', label: 'Nombre' }
                    - { property: 'documento', type: 'text', label: 'Documento' }
        Clientes:
              class: App\Entity\Clientes
        Gasolineras:
              class: App\Entity\Gasolineras
              form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'nombre', type: 'text', label: 'Nombre' }
                    - { property: 'direccion', type: 'text', label: 'Direccion' }
                    - { property: 'codigoPostal', type: 'text', label: 'Código Postal' }
                    - { property: 'nombreEncargado', type: 'text', label: 'Nombre Encargado' }
                    - { property: 'telefonoEncargado', type: 'text', label: 'Teléfono Encargado' }
                    - { property: 'delegacion', type: 'entity', label: 'Delegacion', type_options: { class: 'App\Entity\Delegacion', required: true, multiple: false } }

        PuntosVenta:
              class: App\Entity\PuntoVenta